site_name: "Network Wrangler"
site_url: https://network-wrangler.github.io/network_wrangler
repo_url: https://github.com/network-wrangler/network_wrangler

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
# API contents are so long, disabling these
#   - navigation.expand
    - toc.integrate
    - toc.follow
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - How To: how_to.md
  - Design: design.md
  - Data Models: data_models.md
  - Development: development.md
  - API:
    - Fundamentals: api.md
    - Roadway: api_roadway.md
    - Transit: api_transit.md
  - Networks: networks.md

plugins:
  - autorefs
  - awesome-pages
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - mermaid2
  - mike
# disabling for now since this spits out a log of Unclosed Div warnings
# https://github.com/danielfrg/mkdocs-jupyter/issues/231
#  - mkdocs-jupyter:
#      include_source: True
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://pandera.readthedocs.io/en/stable/objects.inv
          options:
            docstring_section_style: list
            show_source: true
            show_if_no_docstring: false
            show_object_full_path: true
            show_root_full_path: true
            show_root_members_full_path: true
            show_bases: true
            show_inheritance_diagram: true
            separate_signature: true
            signature_crossrefs: true
  - search

watch:
 - network_wrangler

extra:
  version:
    provider: mike
    default: latest

#extra_javascript:


extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css
  - css/extra.css

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - meta
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.smartsymbols
  - smarty
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
      # toc_depth: 3
